"""add users table

Revision ID: 098c72fa4ed5
Revises: 02ec2916ff76
Create Date: 2026-05-18 02:09:15.027652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '098c72fa4ed5'
down_revision: Union[str, None] = '02ec2916ff76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('camera_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'camera_url')
    # ### end Alembic commands ###
